name: GoTo CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/goto/GoTo/
          git pull origin master
          git status
          cd server
          npm install --only=prod
          pm2 restart gotoServer

          cd ../client
          npm install --only=prod
          npm run build
          pm2 restart gotoFrontend
